virt: kvm
addons:
  - name: cilium
    enabled: true
  - name: coredns
    enabled: true
k8s:
  containerized-cplane:
  cluster-cidr: 10.200.0.0/16
  cluster-dns: 10.32.0.10
  kube-proxy: false
  containerd-mirror:
    enabled: false
kvm:
  network: nat
  kickstart: kvm.text.ks.cfg
  os-variant: almalinux9
vm:
  linux: alma9
  create-template: true
  template-vmname: alma9.7
vms:
  - name: kronos
    cpu: 2
    mem: 6144
    ip: 200
    disk:
    pod-cidr: 10.200.0.0/24
  - name: atlas
    cpu: 2
    mem: 6144
    ip: 201
    disk:
    pod-cidr: 10.200.1.0/24
  - name: hyperion
    cpu: 2
    mem: 6144
    ip: 202
    disk:
    pod-cidr: 10.200.2.0/24
  - name: perses
    cpu: 2
    mem: 6144
    ip: 202
    disk:
    pod-cidr: 10.200.3.0/24
cluster:
  admin-kubeconfig: /home/eace/projects/desktop-kubernetes/generated/kubeconfig/admin.kubeconfig
  priv-key: /home/eace/projects/desktop-kubernetes/generated/kickstart/id_ed25519
